### ISSUE TITLE
Beta checklist

### ISSUE THREAD

**Issue by tvolkert** [tvolkert/sci#1]
- [ ] don't show any timesheets in summary view if there aren't any
 - [ ] don't show any expense reports in summary view if there aren't any
 - [ ] don't show any accomplishments in summary view if there aren't any
 - [ ] certify checkbox is not enabled on unsubmitted invoice
 - [ ] round and clip the amounts in expense report cells
 - [ ] don't allow editing of expenses after invoice is submitted
 - [ ] saving data doesn't post the correct blob
 - [ ] maybe bold the red numbers in the expense reports?
 - [ ] remove expense report date range - use invoice date range (keep data model)
 - [ ] disallow creating an expense in the future
 - [ ] wire up delete expense(s)
